#!/bin/sh

echo "init脚本" > /mnt/sda1/112.txt
uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci
cd /usr/bin
mv ssh dropbear-ssh
mv scp dropbear-scp
ln -s /usr/bin/openssh-ssh ssh
ln -s /usr/bin/openssh-scp scp
ln -nsf /mnt/sda1/portal/wifidog /www/wifidog
ls -l s?? >> /mnt/sda1/112.txt
#重设无线
echo "重设无线" >> /mnt/sda1/112.txt
uci set wireless.radio0.country=CN
uci set wireless.radio0.channel='9'
uci set wireless.radio0.txpower=9
uci set wireless.radio1.country=CN
uci set wireless.radio1.disabled='1'
uci delete wireless.@wifi-iface[0]
uci delete wireless.@wifi-iface[0]
uci delete wireless.@wifi-iface[0]
uci delete wireless.@wifi-iface[0]
uci delete wireless.default_radio0
uci delete wireless.default_radio1
uci set wireless.wf0=wifi-iface
uci set wireless.wf0.device='radio0'
uci set wireless.wf0.mode='ap'
uci set wireless.wf0.network='lcrm2'
uci set wireless.wf0.ssid='7907298'
uci set wireless.wf0.encryption='psk2'
uci set wireless.wf0.key='666666666'
uci set wireless.wf1=wifi-iface
uci set wireless.wf1.device='radio0'
uci set wireless.wf1.mode='ap'
uci set wireless.wf1.encryption='none'
uci set wireless.wf1.ssid='先拿馒头再打菜不得劲'
uci set wireless.wf1.network='lan'
uci set wireless.wf2=wifi-iface
uci set wireless.wf2.device='radio0'
uci set wireless.wf2.mode='ap'
uci set wireless.wf2.encryption='none'
uci set wireless.wf2.ssid='打完菜回头拿馒头？'
uci set wireless.wf2.network='lan'
uci set wireless.wf3=wifi-iface
uci set wireless.wf3.device='radio0'
uci set wireless.wf3.mode='ap'
uci set wireless.wf3.encryption='none'
uci set wireless.wf3.ssid='哎！都不得劲。咋整呢'
uci set wireless.wf3.network='lan'
uci commit wireless
/etc/init.d/network reload
wifi down
wifi up
[ -x "/etc/init.d/frp" ] && {
	echo "重设frp" >> /mnt/sda1/112.txt
	uci set frp.common=frp
	uci set fuci set rp.common.log_max_days='1'
	uci set frp.common.login_fail_exit='0'
	uci set frp.common.enable_cpool='0'
	uci set frp.common.time='40'
	uci set frp.common.tcp_mux='1'
	uci set frp.common.vhost_http_port='80'
	uci set frp.common.vhost_https_port='443'
	uci set frp.common.server_port='7000'
	uci set frp.common.log_level='info'
	uci set frp.common.enable_http_proxy='0'
	uci set frp.common.protocol='tcp'
	uci set frp.common.server_addr='frp1.chuantou.org'
	uci set frp.common.token='www.xxorg.com'
	uci set frp.common.enabled='1'
	uci delete frp.@proxy[0]
	uci add frp proxy
	uci set frp.@proxy[0]=proxy
	uci set frp.@proxy[0].type='http'
	uci set frp.@proxy[0].domain_type='subdomain'
	uci set frp.@proxy[0].subdomain='wzslrb'
	uci set frp.@proxy[0].local_ip='127.0.0.1'
	uci set frp.@proxy[0].local_port='80'
	uci set frp.@proxy[0].proxy_protocol_version='disable'
	uci set frp.@proxy[0].use_compression='1'
	uci set frp.@proxy[0].remark='小房b70'
	uci set frp.@proxy[0].enable='1'
	uci commit frp
	service frp restart
}

[ -x "/etc/init.d/vsftpd" ] && {
echo "重设vsftpd" >> /mnt/sda1/112.txt
uci set vsftpd.listen.pasv_min_port='50000'
uci set vsftpd.listen.pasv_max_port='51000'
uci commit vsftpd
service vsftpd restart
}

[ -x "/etc/init.d/wifidogx" ] && {
#第二行后面插入pwd
#apfree-wifidog_4.08.1771-4 修复bug
#sed -i '2apwd' /etc/init.d/wifidogx
echo "重设wifidogx" >> /mnt/sda1/112.txt
sed -i '/" "disabled"/s/0/1/g' /etc/init.d/wifidogx
sed -i '/= "0" ]; then/s/0/1/g' /etc/init.d/wifidogx
sed -i '/if.*APFREE_/s/-s/! &/g' /etc/init.d/wifidogx
sed -i '/if.*APFREE_/s/\&/|/g' /etc/init.d/wifidogx
uci set wifidogx.@wifidog[0]=wifidog
uci set wifidogx.@wifidog[0].gateway_interface='br-lan'
uci set wifidogx.@wifidog[0].auth_server_path='/wifidog/'
uci set wifidogx.@wifidog[0].check_interval='60'
uci set wifidogx.@wifidog[0].client_timeout='5'
#有线通过
uci set wifidogx.@wifidog[0].wired_passed='1'
uci set wifidogx.@wifidog[0].auth_server_hostname='192.168.200.1'
uci set wifidogx.@wifidog[0].auth_server_port='80'
#是否禁用
uci set wifidogx.@wifidog[0].disabled='0'
#线程池模式
uci set wifidogx.@wifidog[0].pool_mode='1'
#线程号
uci set wifidogx.@wifidog[0].thread_number='5'
#队列大小
uci set wifidogx.@wifidog[0].queue_size='20'
uci set wifidogx.@wifidog[0].enable='1'
uci commit wifidogx
service wifidogx restart | tee /mnt/sda1/112wifidogx.log
service wifidogx stop
}

#主机短别名
sed -i 's/.*localhost ip6.*/& h/g' /etc/hosts

echo "主机短别名" >> /mnt/sda1/112.txt
#cat /etc/hosts >> /mnt/sda1/112.txt

[ -s "/usr/share/AdGuardHome/links.txt" ] && {
echo 更新AdGuard Home升级路径 >> /mnt/sda1/112.txt
sed -i '/\.tar\.gz/s/\.tar/_softfloat\.tar/' /usr/share/AdGuardHome/links.txt
}

[ -s "/etc/firewall.user" ] && {
echo 注释防火墙规则iptables 53 >> /mnt/sda1/112.txt
sed -i '/^[^#]/s/.*/# &/' /etc/firewall.user
}

exit 0
