#!/bin/sh

echo "init脚本" > /mnt/sda1/112.txt
uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci
cd /usr/bin
mv ssh dropbear-ssh
mv scp dropbear-scp
ln -s /usr/bin/openssh-ssh ssh
ln -s /usr/bin/openssh-scp scp

[ -d "/mnt/sda1/portal/wifidog" ] && ln -nsf /mnt/sda1/portal/wifidog /www/wifidog

[ -x "/etc/init.d/vsftpd" ] && {
echo "重设vsftpd" >> /mnt/sda1/112.txt
uci set vsftpd.listen.pasv_min_port='50000'
uci set vsftpd.listen.pasv_max_port='51000'
uci commit vsftpd
service vsftpd restart | tee -ai /mnt/sda1/112.txt
}

[ -x "/etc/init.d/wifidogx" ] && {
#第二行后面插入pwd
#apfree-wifidog_4.08.1771-4 修复bug
#sed -i '2apwd' /etc/init.d/wifidogx
echo "重设wifidogx" >> /mnt/sda1/112.txt
sed -i '/" "disabled"/s/0/1/g' /etc/init.d/wifidogx
sed -i '/= "0" ]; then/s/0/1/g' /etc/init.d/wifidogx
sed -i '/if.*APFREE_/s/-s/! &/g' /etc/init.d/wifidogx
sed -i '/if.*APFREE_/s/\&/|/g' /etc/init.d/wifidogx
uci set wifidogx.@wifidog[0]=wifidog
uci set wifidogx.@wifidog[0].gateway_interface='br-lan'
uci set wifidogx.@wifidog[0].auth_server_path='/wifidog/'
uci set wifidogx.@wifidog[0].check_interval='60'
uci set wifidogx.@wifidog[0].client_timeout='5'
#有线通过
uci set wifidogx.@wifidog[0].wired_passed='1'
uci set wifidogx.@wifidog[0].auth_server_hostname='192.168.200.1'
uci set wifidogx.@wifidog[0].auth_server_port='80'
#是否禁用
uci set wifidogx.@wifidog[0].disabled='0'
#线程池模式
uci set wifidogx.@wifidog[0].pool_mode='1'
#线程号
uci set wifidogx.@wifidog[0].thread_number='5'
#队列大小
uci set wifidogx.@wifidog[0].queue_size='20'
uci set wifidogx.@wifidog[0].enable='1'
uci commit wifidogx
service wifidogx restart | tee -ai /mnt/sda1/112.txt
service wifidogx stop
}

#主机短别名
sed -i 's/.*localhost ip6.*/& h/g' /etc/hosts

echo "主机短别名" >> /mnt/sda1/112.txt
#cat /etc/hosts >> /mnt/sda1/112.txt

[ -s "/usr/share/AdGuardHome/links.txt" ] && {
echo 更新AdGuard Home升级路径 >> /mnt/sda1/112.txt
sed -i '/\.tar\.gz/s/\.tar/_softfloat\.tar/' /usr/share/AdGuardHome/links.txt
}

[ -s "/etc/firewall.user" ] && {
echo 注释防火墙规则iptables 53 >> /mnt/sda1/112.txt
sed -i '/^[^#]/s/.*/# &/' /etc/firewall.user
service firewall reload | tee -ai /mnt/sda1/112.txt
} 

echo uhttpd 添加 https 访问 >> /mnt/sda1/112.txt
uci add_list uhttpd.main.listen_https='0.0.0.0:443'
uci add_list uhttpd.main.listen_https='[::]:443'
uci commit uhttpd
service uhttpd restart | tee -ai /mnt/sda1/112.txt
rm -f /common || echo .
rm -f /ipq40xx || echo .
echo 添加计划任务关机 >> /mnt/sda1/112.txt
[ -f "/etc/crontabs/root" ] && sed  '$a 35 21 * * * halt' /etc/crontabs/root
echo 修改root密码 >> /mnt/sda1/112.txt
sed -i '/^root/s/.*/root:$1$VZ4w9Iwy$J0\/V2CNV1HoKG9DAHlPrn1:18506:0:99999:7:::/' /etc/shadow
exit 0
